---
# tasks file for apt-packages
- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

# - name: Install nvidia driver
#   apt:
#     name: nvidia-driver
#     state: latest
#   become: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - build-essential
    # PyQt
    - checkinstall
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev 
    - libbz2-dev 
    - swig 
    - liblapack-dev 
    - libdbus-1-3 
    - libglu1-mesa-dev
    # Other Deps
    - libffi6
    - libffi-dev
    - libfreetype6
    - libfreetype6-dev
    - nmap
    - dvipng
    # NFS
    - nfs-common
    # CSStudio
    - openjfx
    # Other
    - rdesktop
    - vim
    - htop
  become: yes
