---
# tasks file for apt-packages
- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

# - name: Install nvidia driver
#   apt:
#     name: nvidia-driver
#     state: latest
#   become: yes

- name: Install xfonts-100-dpi
  apt:
    name: xfonts-100dpi
  become: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"

- name: Install packages
  apt:
    name: "{{ packages }}"
  become: yes
