---
# tasks file for apt-packages
- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

# - name: Install nvidia driver
#   apt:
#     name: nvidia-driver
#     state: latest
#   become: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
  become: yes
